CampusCookery/CampusCookery/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
]

CampusCookery/main/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

#When the user visits the url on the website, the urlpatterns array is searched to find
#the url, if it is found a view from the path object is called with the requesr as the parameter

urlpatterns = [
    path("", views.home_view, name="home"),
    path("articles/", views.articles, name="articles"),
    path("article/<pk>/", views.article_detail, name="article_detail"),
    path("article_create/", views.article_create, name="article_create"),
    path("article_edit/<pk>/", views.article_edit, name="article_edit"),
    path("article_delete/<pk>/", views.article_delete, name="article_delete"),
    path("recipes/", views.recipes, name="recipes"),
    path("recipes_detail/<pk>/", views.recipe_detail, name="recipe_detail"),
    path("recipe_create/", views.recipe_create, name="recipe_create"),
    path("recipe_edit/<pk>/", views.recipe_edit, name="recipe_edit"),
    path("recipe_delete/<pk>/", views.recipe_delete, name="recipe_delete"),
    path("search/", views.search, name="search"),
    path("signup/", views.signup_view, name="signup"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("account/", views.account_view, name="account"),
    path("settings/", views.settings_view, name="settings"),
    path("favourites/", views.favourites, name="favourites"),
    path("faq/", views.faq, name="faq"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CampusCookery/main/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

# Create your models here.
# Create tables by inheriting from the Model class
# Class = Table, object = record in the table, Attributes of the class = fields


class Recipe(models.Model):
    title = models.CharField(max_length=400)
    ingredients = models.TextField(max_length=20000)
    body = models.TextField(max_length=20000)
    calorie_intake = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="main/media/main", null=True)
    time_taken = models.CharField(max_length=100, null=True, blank=True)
    rating = models.IntegerField(max_length=3, null=True, blank=True)

    def __str__(self):
        return self.title


class Article(models.Model):
    title = models.CharField(max_length=400)
    body = models.TextField(max_length=20000)
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="main/media/main", null=True)
    rating = models.IntegerField(max_length=3, null=True, blank=True)

    def __str__(self):
        return self.title


class Tag(models.Model):
    title = models.CharField(max_length=400)
    article = models.ManyToManyField(Article,null=True, blank=True)
    recipe = models.ManyToManyField(Recipe,null=True, blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

# Extended user to include profile picture
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to="profile_pictures/", null=True, blank=True)

    def __str__(self):
        return self.user.username


class Favourite(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, null=True, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, null=True, on_delete=models.CASCADE, blank=True)

class UserRating(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, null=True, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, null=True, on_delete=models.CASCADE, blank=True)
    rating = models.IntegerField(null=True)

class Faq(models.Model):
    question = models.CharField(max_length=2000)
    answer = models.CharField(max_length=2000)

CampusCookery/main/forms.py
from django import forms
from .models import Recipe, Article, Tag, UserProfile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .utils import resize_profile_picture

#This file is used to generate forms that inherit from django ModelForm class
#these forms are needed to make use of django validating techniques#

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ("title", "ingredients", "body", "calorie_intake", "image", "time_taken")

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ("title", "body", "image")

class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ("title",)

class UserSignupForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text="Required.")
    email = forms.EmailField(max_length=254, help_text="Required. Enter a valid email address.")
    profile_picture = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = ("username", "first_name", "email", "password1", "password2", "profile_picture")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.email = self.cleaned_data['email']
        if commit:
            user.save() # Save user, then create User Profile instance

            user_profile = UserProfile.objects.create(user=user)

            # Set profile picture
            if self.cleaned_data['profile_picture']:
                # Crop and resize to 256x256
                cropped_image = resize_profile_picture(self.cleaned_data['profile_picture'])
                user_profile.profile_picture.save(self.cleaned_data['profile_picture'].name, cropped_image, save=False)

            user_profile.save()

        return user

class UserUpdateForm(forms.ModelForm):
    profile_picture = forms.ImageField(required=False)

    class Meta:
        model = User
        # first_name field used for full name, due to django's handling
        # user not able to change username for security reasons
        fields = ("email", "first_name", "username", "profile_picture")

    def save(self, commit=True):
        user = super(UserUpdateForm, self).save(commit=False)
        if commit:
            user.save()
            # Ensure userprofile exists for user (should be redundant)
            if hasattr(user, 'userprofile'):
                user_profile = user.userprofile
            else:
                user_profile = UserProfile(user=user)

            # Set profile picture
            if self.cleaned_data['profile_picture']:
                # Crop and resize to 256x256
                cropped_image = resize_profile_picture(self.cleaned_data['profile_picture'])
                user_profile.profile_picture.save(self.cleaned_data['profile_picture'].name, cropped_image, save=False)
            user_profile.save()
        return user

CampusCookery/main/views.py
from pip._internal import req
from django.db.transaction import commit
from django.shortcuts import render, redirect
from .models import Recipe, Article, Tag, UserProfile, Favourite, UserRating, Faq
from .forms import RecipeForm, ArticleForm, TagForm, UserUpdateForm, UserSignupForm
from django.contrib.auth import login,logout, authenticate, get_user_model




#The function that renders the homepage
def home_view(request):
    context = {
        "recipes": Recipe.objects.all(),
    }
    return render(request, "main/home.html", context)

#The function that renders the signup page if the user sends a get request
#if the user sends a post request, the data is validated and if it is valid,
#a new user is created
def signup_view(request):
    if request.POST:
        form = UserSignupForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserSignupForm()

    context = {
        "form": form,
    }

    return render(request, "main/signup.html", context)

#The function that renders the login page if the user sends a get request
#if the user sends a post request, the data is validated and if it is valid,
#the user is logged in
def login_view(request):
    if request.POST:
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("home")
        else:
            error_message = "Invalid username or password"

            return render(request, "main/login.html", {"error_message": error_message})

    return render(request, "main/login.html")

#The function that logs the user out
def logout_view(request):
    logout(request)
    return redirect("/")

#The function that renders the page with user account page if they are logged in
def account_view(request):
    if not request.user.is_authenticated:
        return redirect("login")
    try:
        user_profile = UserProfile.objects.get(user=request.user)
        recipes = Recipe.objects.filter(author=request.user)
        articles = Article.objects.filter(author=request.user)

        context = {
            'user_profile': user_profile,
            'recipes': recipes,
            'articles': articles
        }
    except:
        context = {}

    return render(request, "main/account.html", context)

#The function that renders the page with the user account edit form if the request type is GET
#If request type is POST, it validates the data and updates the user account details
def settings_view(request):
    """Enables user to edit account, and change theme"""
    if not request.user.is_authenticated:
        return redirect("login")

    if request.POST:
        form = UserUpdateForm(request.POST, request.FILES, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect("account")
    else:
        form = UserUpdateForm(instance=request.user)

    user_profile = UserProfile.objects.get(user=request.user)

    context = {
        'form': form,
        'user_profile': user_profile,
    }

    return render(request, "main/settings.html", context)

#The function that renders the page with all the articles from the db
def articles(request):
    articles = Article.objects.all()
    context = {"articles": articles}

    return render(request, "main/articles.html", context)

#The function that renders the page with the details of the certain article
def article_detail(request, pk):
    article = Article.objects.get(id=pk)
    if request.method == "POST" and request.user.is_authenticated:
        if request.POST.get("rating") is not None:
            try:
                ur = UserRating.objects.get(user=request.user, article=article)
                ur.delete()
            except:
                pass
            ur = UserRating.objects.create(user=request.user, article=article, rating=request.POST.get("rating"))
            ur.save()

        if request.POST.get("fav") == "true":
            # Ensure favourite cannot be added multiple times
            if not Favourite.objects.filter(user=request.user, article=article).exists():
                fav = Favourite.objects.create(user=request.user, article=article)
                fav.save()
        else:
            fav = Favourite.objects.filter(user=request.user, article=article).first()
            if fav:
                fav.delete()

    rating_sum = 0
    rating_cnt = 0
    rating = None
    for r in UserRating.objects.filter(article=article):
        if r.rating is not None:
            rating_sum += int(r.rating)
            rating_cnt += 1
    if rating_cnt != 0:
        rating = rating_sum / rating_cnt
    try:
        favourite = Favourite.objects.get(user=request.user, article=article)
    except:
        favourite = None
    context = {
        "article": article,
        "rating": rating,
        "favourite": favourite,
    }
    return render(request, "main/article.html", context)

#The function that renders the page with article create form if the request type is get
#If the request type is post, it validates the data and creates a new article in the db
def article_create(request):
    if not request.user.is_authenticated:
        return redirect("login")
    if request.POST:
        form = ArticleForm(request.POST, request.FILES)
        print(request.POST)
        if form.is_valid():
            new_article = form.save(commit=False)
            new_article.author = request.user
            new_article.save()
            tags = request.POST.getlist("tags")
            for tag in tags:
                t = Tag.objects.get(title=tag)
                t.article.add(new_article)
            return redirect("/")
    else:
        form = ArticleForm()

    context = {
        "form": ArticleForm,
        "tags": Tag.objects.all(),
    }

    return render(request, "main/article_create.html", context)

#The function that renders the page with article edit form if the request type is get
#If the request type is post, it validates the data and edits the article in the db
def article_edit(request, pk):
    edited_article = Article.objects.get(id=pk)

    if not request.user.is_authenticated or not request.user == edited_article.author:
        return redirect("login")

    if request.POST:
        form = ArticleForm(request.POST, request.FILES, instance=edited_article)

        if form.is_valid():
            form.save()

            tags = request.POST.getlist("tags")
            try:
                for tag in Tag.objects.get(article=edited_article):
                    tag.article.remove(edited_article.id)
            except:
                pass
            for tag in tags:
                t = Tag.objects.get(title=tag)
                t.article.add(edited_article.id)
            return redirect("/")
    else:
        form = ArticleForm(instance=edited_article)

    context = {
        "pk": pk,
        "form": form,
    }
    return render(request, "main/article_edit.html", context)

#The function to delete an article from the db
def article_delete(request, pk):
    if request.user.is_authenticated:
        article_to_delete = Article.objects.get(id=pk)
        if request.user == article_to_delete.author:
            if request.POST:
                article_to_delete.delete()
        else:
            return redirect("login")
    else:
        return redirect("login")

#The function that renders the page with all the recipes from the db
def recipes(request):
    tags = Tag.objects.prefetch_related("recipe")

    context = {tags: tags}

    return render(request, "main/recipes.html", context)

#The function that renders the page with the details of the certain recipe
def recipe_detail(request, pk):
    recipe = Recipe.objects.get(id=pk)
    if request.method == "POST" and request.user.is_authenticated:
        if request.POST.get("rating") is not None:
            try:
                ur = UserRating.objects.get(user=request.user, recipe=recipe)
                ur.delete()
            except:
                pass
            ur = UserRating.objects.create(user=request.user, recipe=recipe, rating=request.POST.get("rating"))
            ur.save()

        if request.POST.get("fav") == "true":
            # Ensure favourite cannot be added multiple times
            if not Favourite.objects.filter(user=request.user, recipe=recipe).exists():
                fav = Favourite.objects.create(user=request.user, recipe=recipe)
                fav.save()
        else:
            fav = Favourite.objects.filter(user=request.user, recipe=recipe).first()
            if fav:
                fav.delete()

    rating_sum = 0
    rating_cnt = 0
    rating = None
    for r in UserRating.objects.filter(recipe=recipe):
        if r.rating is not None:
            rating_sum += int(r.rating)
            rating_cnt += 1
    if rating_cnt != 0:
        rating = rating_sum / rating_cnt
    try:
        favourite = Favourite.objects.get(user=request.user, recipe=recipe)
    except:
        favourite = None
    context = {
        "recipe": recipe,
        "rating": rating,
        "favourite": favourite,
    }
    return render(request,"main/recipe.html", context)

#The function that renders the page with recipe create form if the request type is get
#If the request type is post, it validates the data and creates a new recipe in the db
def recipe_create(request):
    if not request.user.is_authenticated:
        return redirect("login")

    if request.POST:
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            new_recipe = form.save(commit=False)
            new_recipe.author = request.user
            new_recipe.save()
            tags = request.POST.getlist("tags")
            for tag in tags:

CampusCookery/main/templates/components/article_card.html
<a href="{%url 'article_detail' article.id%}" class="card">
    <img src="{{article.image.url}}" alt="Article Image" />
    <div class="card-info">
        <div class="card-header">
            <h3 class="card-title">{{ article.title }}</h3>

            <p>{{ article.body|safe|slice:":50" }}...</p>
        </div>

        <div class="card-tags">
            <div class="tag">
                {{article.created_at|date:"F j, Y"}}
            </div>

            {% for tag in article.tag_set.all %}
                <div class="tag">{{tag.title}}</div>
            {%endfor%}


            {% if recipe.rating %}
                <div class="tag">
                    <div class="stars">{{recipe.rating}}</div>
                </div>
            {% endif %}
        </div>
    </div>
</a>

CampusCookery/main/templates/components/back_button.html
<button onclick="window.history.back()" class="back-button">
    <i class="fa-solid fa-arrow-left"></i>
</button>

CampusCookery/main/templates/components/darkmode_toggle.html
<div class="toggle-container">
    <input type="checkbox" id="theme-switch" />
    <label for="theme-switch">
        <svg
            class="moon"
            xmlns="http://www.w3.org/2000/svg"
            height="24px"
            viewBox="0 -960 960 960"
            width="24px"
            fill="#5f6368"
        >
            <path
                d="M480-120q-150 0-255-105T120-480q0-150 105-255t255-105q14 0 27.5 1t26.5 3q-41 29-65.5 75.5T444-660q0 90 63 153t153 63q55 0 101-24.5t75-65.5q2 13 3 26.5t1 27.5q0 150-105 255T480-120Zm0-80q88 0 158-48.5T740-375q-20 5-40 8t-40 3q-123 0-209.5-86.5T364-660q0-20 3-40t8-40q-78 32-126.5 102T200-480q0 116 82 198t198 82Zm-10-270Z"
            />
        </svg>
        <svg
            class="sun"
            xmlns="http://www.w3.org/2000/svg"
            height="24px"
            viewBox="0 -960 960 960"
            width="24px"
            fill="#5f6368"
        >
            <path
                d="M480-280q-83 0-141.5-58.5T280-480q0-83 58.5-141.5T480-680q83 0 141.5 58.5T680-480q0 83-58.5 141.5T480-280ZM200-440H40v-80h160v80Zm720 0H760v-80h160v80ZM440-760v-160h80v160h-80Zm0 720v-160h80v160h-80ZM256-650l-101-97 57-59 96 100-52 56Zm492 496-97-101 53-55 101 97-57 59Zm-98-550 97-101 59 57-100 96-56-52ZM154-212l101-97 55 53-97 101-59-57Z"
            />
        </svg>
    </label>
</div>

CampusCookery/main/templates/components/favourite_button.html
{% if user.is_authenticated %}
    <form method="post">
        {% csrf_token %}
        {% if favourite %}
            <input name ="fav" type="hidden" value="false">
            <button type="submit" class="favourite-button">
                <i class="fa-solid fa-heart"></i>
            </button>
        {% else %}
            <input name ="fav" type="hidden" value="true">
            <button type="submit" class="favourite-button">
                <i class="fa-regular fa-heart"></i>
            </button>
        {% endif %}
    </form>
{% endif %}

CampusCookery/main/templates/components/gridview.html
<!-- Pass in: title, grid_recipes or grid_articles -->

{% if grid_recipes or grid_articles %}
<div class="grid-view">
    {% if title  %}
        <h3 class="grid-title">{{ title }}</h3>
    {% endif %}


    <div class="cards-grid">
        {% for recipe in grid_recipes %}
            {% include 'components/recipe_card.html' with recipe=recipe %}
        {% endfor %}

        {% for article in grid_articles %}
            {% include 'components/article_card.html' with article=article %}
        {% endfor %}
    </div>
</div>
{% endif %}

CampusCookery/main/templates/components/navbar.html
<div class="navigation-bar">
    <div>
        <a href="{%url 'home' %}" class="logo">Campus Cookery</a>

        <div class="nav-items">
            <div class="{% if request.path == '/recipes/' %}nav-current{% endif %}">
                <i class="fa-solid fa-utensils"></i>
                <a href="{%url 'recipes' %}">Recipes</a>
            </div>
            <div class="{% if request.path == '/articles/' %}nav-current{% endif %}">
                <i class="fa-solid fa-book"></i>
                <a href="{%url 'articles' %}">Articles</a>
            </div>
            <div class="{% if request.path == '/favourites/' %}nav-current{% endif %}">
                <i class="fa-solid fa-heart"></i>
                <a href="{% url 'favourites' %}">Favourites</a>
            </div>
            <div class="{% if request.path == '/faq/' %}nav-current{% endif %}">
                <i class="fa-solid fa-user-group"></i>
                <a href="{%url 'faq'%}">FAQs</a>
            </div>
        </div>
    </div>

    <div class="nav-user">
        <!-- settings button -->
        <a class="{% if request.pah == 'settings' %}nav-current{% endif %} settings" href ="{% url 'settings' %}">
            <i class="fa-solid fa-cog"></i>
        </a>

        {% if user.is_authenticated %}
            {% include 'components/profilepic.html' %}
            <a class="{% if request.path == '/account/' %}nav-current{% endif %}" href="{%url 'account' %}">{{ user.username }}</a>
        {% else %}
            <a href="{%url 'login' %}">Login / Signup</a>
        {% endif %}
    </div>
</div>

CampusCookery/main/templates/components/navbar_mobile.html
<div class="navigation-bar-mobile">
    <div class="nav-items">
        <a href="{%url 'recipes' %}" class="{% if request.path == '/recipes/' %}nav-current{% endif %}">
            <i class="fa-solid fa-utensils"></i>
        </a>
        <a href="{%url 'articles' %}" class="{% if request.path == '/articles/' %}nav-current{% endif %}">
            <i class="fa-solid fa-book"></i>
        </a>
        <a href="{% url 'favourites' %}" class="{% if request.path == '/favourites/' %}nav-current{% endif %}">
            <i class="fa-solid fa-heart"></i>
        </a>

        <a href="{%url 'faq'%}" class="{% if request.path == '/faq/' %}nav-current{% endif %}">
            <i class="fa-solid fa-user-group"></i>
        </a>

        {% if user.is_authenticated %}
            <a class="{% if request.path == '/account/' %}nav-current{% endif %}" href="{%url 'account' %}">
                {% include 'components/profilepic.html' %}
            </a>
        {% else %}
            <a class="{% if request.path == '/login' or request.path == 'signup' %}nav-current{% endif %}" href="{%url 'login' %}">
                <i class="fa-solid fa-account"></i>
            </a>
        {% endif %}
    </div>
</div>

CampusCookery/main/templates/components/profilepic.html
{% load static %}
<div class="profile-picture">
    {% if user_profile.profile_picture %}
        <img src="{{ user_profile.profile_picture.url }}" alt="">
    {% else %}
        <img src="{% static 'assets/pfp.png' %}" alt="">
    {% endif %}
</div>

CampusCookery/main/templates/components/rating.html
<!-- Zero-javascript approach, each star submits its own rating as its own form. -->
{% if user.is_authenticated %}
    <div class="ratings">
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="rating" value="1">
            <button type="submit">{% if rating > 0 %}★{% else %}☆{% endif %}</button>
        </form>
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="rating" value="2">
            <button type="submit">{% if rating > 1 %}★{% else %}☆{% endif %}</button>
        </form>
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="rating" value="3">
            <button type="submit">{% if rating > 2 %}★{% else %}☆{% endif %}</button>
        </form>
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="rating" value="4">
            <button type="submit">{% if rating > 3 %}★{% else %}☆{% endif %}</button>
        </form>
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="rating" value="5">
            <button type="submit">{% if rating > 4 %}★{% else %}☆{% endif %}</button>
        </form>
    {% endif %}
    </div>

CampusCookery/main/templates/components/recipe_card.html
{% load custom_filters %}

<a href="{%url 'recipe_detail' recipe.id%}" class="card">
    <img src="{{recipe.image.url}}" alt="Recipe Image" />
    <div class="card-info">
        <h3 class="card-title">{{ recipe.title }}</h3>

        <div class="card-tags">
            {% for tag in recipe.tag_set.all %}
                <div class="tag">{{tag.title}}</div>
            {%endfor%}

            <div class="tag">
                <i class="fa-solid fa-clock"></i>{{recipe.time_taken}} min
            </div>

            {% if recipe.rating %}
                <div class="tag">
                    <div class="stars">{{recipe.rating}}</div>
                </div>
            {% endif %}
        </div>
    </div>
</a>

<!--
title
body
calorie_intake
created_at
author
image
time_taken
rating
-->

CampusCookery/main/templates/components/scroll_recipe_cards.html
<!-- Netflix style scrolling cards -->
<div class="scrollable-cards-container">
    <div class="scrollable-title">{{ tag }}</div>
    <div class="scrollable-cards">
        {% for recipe in recipes %}
            {% include 'components/recipe_card.html' with recipe=recipe %}
        {% endfor %}
    </div>
</div>

CampusCookery/main/templates/components/searchbar.html
<form method="get" class="search-container" action="/search/">
    <input
        type="text"
        name="q"
        font="Amatic SC"
        id="searchInput"
        placeholder="Search"
        class="searchbox"
    />
    <button type="submit">
        <i class="fa fa-search"></i>
    </button>

    <!-- Content type recipes or articles name="type" -->
    <input type="hidden" name="type" id="searchTypeInput" value="recipes">
    <i id="searchTypeToggle" title="Recipes" class="fa fa-utensils"></i>

    <!-- Tags -->
    <i id="searchFilterToggle" class="fa fa-list" title="Filter tags"></i>

    <div id="searchFilterModal" class="search-modal hidden">
        <div class="search-tags">
            {% for tag in tags %}
            <label class="tag">
                <input type="checkbox" name="tags" value="{{ tag.title }}">
                {{ tag.title }}
            </label>
            {% endfor %}
        </div>
    </div>
</form>